version: "3.8"

services:
  web:
    build: .
    command: python SalleSpectacle/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - MARIADB_DATABASE=db
      - MARIADB_USER=dev
      - MARIADB_PASSWORD=dev
      - MARIADB_HOST=db
      - MARIADB_PORT=3306

  db:
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=secret
      - MARIADB_DATABASE=db
      - MARIADB_USER=dev
      - MARIADB_PASSWORD=dev
    volumes:
      - mariadb_data:/var/lib/mysql/data
volumes:      
  mariadb_data:
